### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by ionutz** [pistol88/yii2-shop#5]
Problem 1
    - The requested package pistol88/yii2-gallery * is satisfiable by pistol88/y                                  ii2-gallery[dev-master] but these conflict with your requirements or minimum-sta                                  bility.
  Problem 2
    - The requested package pistol88/yii2-tree * is satisfiable by pistol88/yii2                                  -tree[dev-master] but these conflict with your requirements or minimum-stability                                  .
  Problem 3
    - The requested package pistol88/yii2-promocode * is satisfiable by pistol88                                  /yii2-promocode[dev-master] but these conflict with your requirements or minimum                                  -stability.
  Problem 4
    - The requested package pistol88/yii2-seo * is satisfiable by pistol88/yii2-                                  seo[dev-master] but these conflict with your requirements or minimum-stability.
  Problem 5
    - The requested package pistol88/yii2-filter * is satisfiable by pistol88/yi                                  i2-filter[dev-master] but these conflict with your requirements or minimum-stabi                                  lity.
  Problem 6
    - The requested package pistol88/yii2-field * is satisfiable by pistol88/yii                                  2-field[dev-master] but these conflict with your requirements or minimum-stabili                                  ty.
  Problem 7
    - The requested package pistol88/yii2-relations * is satisfiable by pistol88                                  /yii2-relations[dev-master] but these conflict with your requirements or minimum                                  -stability.

**Comment by pistol88** [comment]
Откройте composer.json вашего проекта и измените параметр minimum-stability на dev.
