### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by SuperBilge** [pistol88/yii2-shop#8]
В процессе установки модуля возникало довольно много вопросов на некоторых шагах.
В ридме ответов на эти вопросы я не нашел. Приходилось находить ответы самому. Я думаю, было бы неплохо осветить некоторые шаги небольшими инструкциями. Например, как привязать контроллер модуля в конфигах для urlManager. Или как выставить права администратора юзерам. Во время проведения миграций, вылетала ошибка @webroot/assets и @web/assets invalid path. Думаю это помогло бы многим, кто желает установить данный модуль, ибо его функционал довольно привлекателен для начинающих программистов Yii. Заранее спасибо за Ваш ответ.

**Comment by SuperBilge** [comment]
И для развернутого гайда можно привести пример установки модуля на примере шаблона advanced

**Comment by pistol88** [comment]
Модуль в стадии очень глубокой разработки, никто пока что не знает, что получится в итоге, любая инструкция пока что быстро становится неактуальной.

Постараюсь выделить время и причесать все, чтобы все было более очевидным.

**Comment by pistol88** [comment]
https://github.com/dvizh/shop-skeleton - вот скелетон, который значительно упростит старт.
