### ISSUE TITLE
объект common\modules\pistol88 

### ISSUE THREAD

**Issue by onmotion** [pistol88/yii2-shop#9]
Приветствую.

Во всех js скриптах глобальный объект называется common\modules\pistol88, что приводит к возникновению ошибок. Переименовал в просто pistol88. Соответственно во всех стилях и шаблонах тоже пришлось менять.

Возможно какие-нибудь браузеры и позволяют такие наименования, у меня Chrome 58 нет, да и JSHint в PHPStorm ругается. Еще сравнение типов с помощью == вместо ===.

**Comment by pistol88** [comment]
Не совсем понял, в каком JS глобальный объект так называется? Что за ошибка возникает?

**Comment by onmotion** [comment]
Оу, сорри, это меня уже глючит)) все ок там.

Разве что операторы сравнения == поменять, но это не ошибка. 

Спасибо.
